// MOCK — fixture from S151 DIMENSION_LIFT_REGISTRY; will wire to /api/verifier/records later.
// 数据来源：backend/candidate_funnel/evaluation.py DIMENSION_LIFT_REGISTRY（12 维 §44 已跑值）。
// 三窗口对比来自 specs/S159-§44应用规约v2/spec.md（overnight_gap_decomposition.py, 3362 obs）。
// overfit_stats 全 null（待建，S161 wire backtest-overfit 后填实）。
// ci_low/ci_high 不在 S151 REGISTRY → null + "待 v2 verifier 跑出"（field source map，不臆造）。
// updated_commit/updated_at → null + "待回溯 task 填充"（S161 v2 已加字段，回溯 task 未跑）。
// pbo → null；selection dims 标 "待建 (not-yet-wired)"，event verdict 标 "N/A (single-strategy)"。
// v2: 5-value enum（not_validated）+ edge_type/tradeable/event_metrics/event_status/dsr_method/n_effective/data_snapshot_id;
//     三窗口去 IC/lift（S159 §5A）; gap 非 REGISTRY 维是 §3 event verdict（edge_type=event, 在 recorder records）。
import type {
  DimensionValidationRecord,
  RecorderRecord,
  ThreeWindowCompare,
  OverfitStats,
} from "@/lib/verifier-contract";
import { statusFromChinese } from "@/lib/verifier-contract";

// S159 三窗口分解（universe-level baseline，非 per-dimension）
// 来源：overnight_gap_decomposition.py, baostock kline_cache + gene_scores 3362 obs
// per-dimension 三窗口对比需 S161 daily-bar run（TODO）
// v2: 去 IC/lift — S159 §5A: mean+中位+胜率+base_rate only
const S159_WINDOW_BASELINE: ThreeWindowCompare = {
  overnight_gap: {
    mean: 0.013, // +1.30% ← 真 event edge（合 Chen2017）
    median: 0.0028, // +0.28%
    win_rate: 0.543, // 54.3%
    base_rate: null, // TODO S161 daily-bar run
  },
  d1_intraday: {
    mean: 0.0003, // +0.03%
    median: 0.0, // 0.00%
    win_rate: 0.462, // 46.2%
    base_rate: null,
  },
  path: {
    mean: 0.0067, // +0.67%
    median: -0.03, // -3.00% ← 反转负段
    win_rate: 0.363, // 36.3%
    base_rate: null,
  },
};

// S165 R1: overfit 占位——全 null，S161 wire backtest-overfit skill 后填实
const OVERFIT_PLACEHOLDER: OverfitStats = {
  pbo: null,
  cscv: null,
  dsr: null,
  haircut: null,
  min_trl: null,
};

const FROZEN_COMMIT = "b1aba21"; // S151 spec 首次 commit（2026-09-05）

// v2: REGISTRY 12 维皆为 selection-layer
// (edge_type=selection, tradeable=false, event_metrics=null, event_status=null, dsr_method=N/A, n_effective=null)
// gap 非 REGISTRY 维——是 §3 event verdict（edge_type=event），在下方 recorder records 独立呈现。

// S151 REGISTRY 12 维 → DimensionValidationRecord
// 原始 validation_status 为中文，经 statusFromChinese 映射为 S161 英文枚举
// v2: "未validated"→not_validated（非 underpowered——breakout n=43691 是 lift 弱非 n 小）
export const dimensionValidationMocks: readonly DimensionValidationRecord[] = [
  {
    dimension_id: "gene_score",
    label: "gene 综合分",
    lift: 0.03,
    ci_low: null,
    ci_high: null,
    n: 2332,
    n_effective: null,
    days_robust: 38,
    status: statusFromChinese("劣于随机"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.1,
    source_script: "tools/gene_score_directionality.py",
    note: "rho≈0.030 robust null，无方向预测力（52bedf8）",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "breakout",
    label: "breakout_20d",
    lift: 1.363,
    ci_low: null,
    ci_high: null,
    n: 43691,
    n_effective: null,
    days_robust: 42,
    status: statusFromChinese("未validated"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.5,
    source_script: "tools/kline_ta_validation.py",
    note: "4 方向特征里最弱，CI 不重叠非纯噪声但 <2x",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "turnover",
    label: "换手剔除(>30%)",
    lift: 0.9979,
    ci_low: null,
    ci_high: null,
    n: 14366,
    n_effective: null,
    days_robust: 167,
    status: statusFromChinese("劣于随机"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.1,
    source_script: "tools/first_board_layer_lift.py --baostock",
    note: "换手>30% 剔除后 lift<1，越剔越差（本会话跑）",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "seal_amount",
    label: "封板质量(炸板/封单)",
    lift: 0.9897,
    ci_low: null,
    ci_high: null,
    n: 177,
    n_effective: null,
    days_robust: 5,
    status: statusFromChinese("探索性"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 1.0,
    source_script: "tools/first_board_layer_lift.py --baostock-history",
    note: "5 日弱样本方向性但非 robust，待 60 日复验",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "path_lift",
    label: "选股整体 path_lift",
    lift: 0.978,
    ci_low: null,
    ci_high: null,
    n: 627,
    n_effective: null,
    days_robust: 44,
    status: statusFromChinese("劣于随机"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.1,
    source_script: "tools/s145_recompute_path.py",
    note: "选股整体 path_lift<1，s145 敏感性 5 组 0.87-0.97 robust",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "first_plate_h2",
    label: "盘中 H2 早封板(<=10:00)",
    lift: 0.8273,
    ci_low: null,
    ci_high: null,
    n: 1125,
    n_effective: null,
    days_robust: 31,
    status: statusFromChinese("劣于随机"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.1,
    source_script: "tools/first_plate_h2_lift.py --full",
    note: "S152 baostock 5min 早封板 lift<1（null_p95=1.048，pass_filter_edge=False）；盘中封板时间无 edge；caveat: T+0 o2c+5min 粒度",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "late_lock",
    label: "盘中晚封板/尾盘突袭(>14:00)",
    lift: 1.3559,
    ci_low: null,
    ci_high: null,
    n: 422,
    n_effective: null,
    days_robust: 31,
    status: statusFromChinese("未validated"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.5,
    source_script: "tools/first_plate_h2_lift.py --full",
    note: "S152 全量唯一弱正（>null_p95=1.117 pass_filter_edge=True 但<2）；尾盘突袭 end_of_day_sneak 近似；raw-shadow 观察，不驱动交易；caveat: T+0 o2c+5min 粒度+top15/full 一致",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "vol_surge_ref",
    label: "vol_surge(参照,非选股层,T-1非盘中)",
    lift: 1.974,
    ci_low: null,
    ci_high: null,
    n: 43691,
    n_effective: null,
    days_robust: 42,
    status: statusFromChinese("未validated"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.5,
    source_script: "tools/kline_ta_validation.py",
    note: "S155 证伪：pooled 2.046(全局quintile look-ahead)→per-T 1.974(<2未validated); net path-winrate 扣0.70%cost=0.945x 劣于随机(cost-killed,非tradeable); 原'盘中维度'是mislabel(实为T-1特征); 参照不参与选股降权",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "platform_breakout",
    label: "平台突破(breakout精细化)",
    lift: 1.0791,
    ci_low: null,
    ci_high: null,
    n: 946,
    n_effective: null,
    days_robust: 130,
    status: statusFromChinese("未validated"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.5,
    source_script: "tools/platform_breakout_lift.py",
    note: "S153 R7 tight0.9606劣于随机/confirm1.0791/both1.2177全<2x is_sig=False; regime_bull both1.4152 p=0.018 但 Bonferroni α_adj=0.00625 fail; walk-forward0.77-1.05; pre_register 74295b9; 闭合 breakout 家族",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "low_absorption",
    label: "低吸缩量(C3 vol_brk<1)",
    lift: 1.0015,
    ci_low: null,
    ci_high: null,
    n: 92308,
    n_effective: null,
    days_robust: 145,
    status: statusFromChinese("未validated"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.5,
    source_script: "tools/low_absorption_c3_lift.py",
    note: "S153 R8 C3 vol_brk<1.0 lift≈1.0 null n=92308; regime_strong0.997<1; walk-forward0.99-1.04; pre_register 74295b9; 无 edge",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "sector_heat",
    label: "板块热度→次日新涨停",
    lift: 1.359,
    ci_low: null,
    ci_high: null,
    n: 466,
    n_effective: null,
    days_robust: 41,
    status: statusFromChinese("未validated"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.5,
    source_script: "tools/sector_heat_validation.py",
    note: "5 定义全<2x(top1 1.23/top3 1.07/top5 1.29/zt≥3 1.359 CI不重叠/zt≥5 1.28); n=41日 eastmoney_live; 情绪/regime 是 moderator 非 standalone signal; 60日后复验",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
  {
    dimension_id: "sector_phase",
    label: "板块周期相位",
    lift: null,
    ci_low: null,
    ci_high: null,
    n: 2319,
    n_effective: null,
    days_robust: 25,
    status: statusFromChinese("劣于随机"),
    edge_type: "selection",
    tradeable: false,
    event_metrics: null,
    event_status: null,
    weight_multiplier: 0.1,
    source_script: "tools/sector_phase_regression.py",
    note: "winrate 0.52-0.60 非单调(启动0.563→发酵0.565→高潮0.605→退潮0.569回落); CI 重叠; label-only(B); 修饰方向单调=False; 无 edge",
    dsr_method: "N/A",
    three_window_compare: S159_WINDOW_BASELINE,
    overfit_stats: OVERFIT_PLACEHOLDER,
    frozen_commit: FROZEN_COMMIT,
    updated_commit: null,
    updated_at: null,
    data_snapshot_id: null,
    layer: "selection",
  },
] as const;

// S161 R4: RecorderRecord mock（实验追踪记录，3 条）
// v2: gap 是 §3 event verdict（edge_type=event, event_metrics populated, event_status=event_thin_positive）
export const recorderRecordMocks: readonly RecorderRecord[] = [
  {
    recorder_id: "rec_gap_20260905_001",
    data_snapshot_id: null, // v2: as_of PIT bundle-id, 待 S162 pit_store
    input_snapshot_hash: "sha256:a3f1e2b8c4d5...",
    params: {
      window: "overnight_gap",
      method: "day_paired",
      bonferroni_k: 8,
      cost_bps: 40,
      walk_forward: true,
      universe: "ths_limit_up_pool",
    },
    n_trials: 20,
    verdict: {
      status: "underpowered",
      lift: 1.3,
      ci_low: null,
      ci_high: null,
      p_bonferroni: null,
      dsr: null,
      pbo: null,
      haircut: null,
      min_trl: null,
      days_robust: 14,
      n: 899,
      n_effective: null,
      edge_type: "event",
      tradeable: false,
      event_metrics: {
        mean_return: 0.013, // +1.30% gross
        net_mean: 0.009, // +0.93% net (after 40bps cost)
        win_rate: 0.543, // 54.3%
        t_stat_day_clustered: 10.65, // day-clustered one-sample t-test
        n_event: 899,
        base_rate: null, // TODO S161 daily-bar run
      },
      event_status: "event_thin_positive",
      dsr_method: "lenient_single_estimate",
      frozen_commit: FROZEN_COMMIT,
      updated_commit: null,
      updated_at: null,
      data_snapshot_id: null,
      note: "gap hypothesis 14 天 underpowered，待 42 天 daily-bar 复验（S159 自相矛盾 caveat）",
    },
    timestamp: "2026-09-05T16:30:00Z",
  },
  {
    recorder_id: "rec_path_lift_20260905_002",
    data_snapshot_id: null,
    input_snapshot_hash: "sha256:7e9c1f2a3b8d...",
    params: {
      window: "path",
      method: "day_paired",
      bonferroni_k: 8,
      cost_bps: 70,
      walk_forward: true,
      universe: "gene_scores_selection",
    },
    n_trials: 20,
    verdict: {
      status: "falsified",
      lift: 0.978,
      ci_low: null,
      ci_high: null,
      p_bonferroni: null,
      dsr: null,
      pbo: null,
      haircut: null,
      min_trl: null,
      days_robust: 44,
      n: 627,
      n_effective: null,
      edge_type: "selection",
      tradeable: false,
      event_metrics: null,
      event_status: null,
      dsr_method: "N/A",
      frozen_commit: FROZEN_COMMIT,
      updated_commit: null,
      updated_at: null,
      data_snapshot_id: null,
      note: "选股整体 path_lift<1（s145 敏感性 5 组 0.87-0.97 robust）",
    },
    timestamp: "2026-09-05T17:00:00Z",
  },
  {
    recorder_id: "rec_breakout_20260905_003",
    data_snapshot_id: null,
    input_snapshot_hash: "sha256:f2a8c1e9b4d7...",
    params: {
      window: "path",
      method: "day_paired",
      bonferroni_k: 4,
      cost_bps: 0,
      walk_forward: false,
      universe: "kline_ta_validation",
    },
    n_trials: 4,
    verdict: {
      status: "not_validated",
      lift: 1.363,
      ci_low: null,
      ci_high: null,
      p_bonferroni: null,
      dsr: null,
      pbo: null,
      haircut: null,
      min_trl: null,
      days_robust: 42,
      n: 43691,
      n_effective: null,
      edge_type: "selection",
      tradeable: false,
      event_metrics: null,
      event_status: null,
      dsr_method: "N/A",
      frozen_commit: FROZEN_COMMIT,
      updated_commit: null,
      updated_at: null,
      data_snapshot_id: null,
      note: "breakout 4 方向特征最弱 CI 不重叠但<2x；not_validated（n=43691 不欠样本，是 lift 弱非 n 小）",
    },
    timestamp: "2026-09-05T17:15:00Z",
  },
] as const;
