#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""gap regime stratified re-verification.

Question: is gap overnight net negative (-0.40%, win 40.1%) a regime artifact?
120d (~6 months) might be single-regime (bear market -> gap zhitigu performs poorly).

Splits 120d first-board gap returns into bull/bear/range market regimes
based on Shanghai Composite Index (sh.000001) MA20 position + slope, then
computes per-regime net return + win rate + n_days + t-stat.

Reuses:
  - gap computation logic from s44_gap_run_60d (real per-trade cost from
    engine.accounting.gap_net_return: 5 yuan min commission + stamp duty +
    slippage, scaled to each trade's notional)
  - .vibe-research/index_ma20_regime.json (pre-computed index close + MA20,
    generated by index_ma20_regime_fetch.py from baostock sh.000001)
  - _s44_wire.wire_verdict for per-regime §44v2 event verdict (S168 pattern)

Regime definition (3-way):
  bull  = close > MA20 AND MA20_slope > 0  (above rising trend)
  bear  = close < MA20 AND MA20_slope < 0  (below falling trend)
  range = everything else                  (crossing / flat / divergence)

MA20_slope = (ma20_today - ma20_yesterday) / ma20_yesterday,
where yesterday = previous trading day (baostock returns trading days only).
"""
from __future__ import annotations

import bisect
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))

from engine.accounting import gap_net_return  # noqa: E402

VR = ROOT / ".vibe-research"
UNIVERSE = VR / "first_board_universe_baostock_120d.json"
KLINE = VR / "baostock_kline_cache.json"
REGIME_CACHE = VR / "index_ma20_regime.json"

TRADE_SIZE = 100  # 1 lot = 100 shares (A-share minimum, conservative retail)
FROZEN_COMMIT = "b4e7446"  # same as s44_gap_run_60d (universe + kline frozen)
MA_WINDOW = 20


# ─── data loading ───────────────────────────────────────────────────────

def load_universe() -> list[dict]:
    """Load 120d first-board universe (same as s44_gap_run_60d)."""
    with open(UNIVERSE, encoding="utf-8") as f:
        data = json.load(f)
    print(f"[universe] window={data['meta']['window']} "
          f"first_board={data['totals']['first_board']}")
    return data["first_boards"]


def build_kline_index():
    """Load kline cache once; build per-code date->index map + trading calendar.

    Same as s44_gap_run_60d.build_kline_index (replicated, not imported,
    because the original is a __main__ script with side-effect imports).
    """
    print("[kline] loading 160MB cache ...")
    with open(KLINE, encoding="utf-8") as f:
        cache = json.load(f)
    print(f"[kline] codes={len(cache)}")
    all_dates: set[str] = set()
    for bars in cache.values():
        for b in bars:
            all_dates.add(b["date"])
    trading_calendar = sorted(all_dates)
    print(f"[calendar] {len(trading_calendar)} trading dates")
    idx_maps: dict[str, dict[str, int]] = {}
    for code, bars in cache.items():
        idx_maps[code] = {b["date"]: i for i, b in enumerate(bars)}
    return cache, idx_maps, trading_calendar


def calendar_next(calendar: list[str], date_str: str) -> str | None:
    """Next trading day after date_str in the calendar."""
    idx = bisect.bisect_left(calendar, date_str)
    if idx < len(calendar) and calendar[idx] == date_str:
        return calendar[idx + 1] if idx + 1 < len(calendar) else None
    if idx < len(calendar):
        return calendar[idx]
    return None


# ─── gap computation (replicated from s44_gap_run_60d) ───────────────────

def compute_gap_series(fbs, cache, idx_maps, calendar):
    """Per-trade gap net return (buy D close, sell D+1 open, real cost).

    Exact same logic as s44_gap_run_60d.compute_gap_series. Replicated here
    to keep this script self-contained (original has __main__ side effects).

    Fixes applied (same as original):
    - date adjacency: bars[i+1] must == calendar_next(D)
    - volume guard: zero-volume bars are suspended (fake returns)
    - adj-epoch check: cache close at D must match universe close_d
    """
    returns: list[float] = []
    dates: list[str] = []
    costs: list[float] = []
    n_unbuyable = n_no_code = n_bad_close = n_suspended = n_adj_mismatch = 0
    for r in fbs:
        code = r["code"]
        d = r["date"]
        close_d = r.get("close")
        if close_d is None or close_d <= 0:
            n_bad_close += 1
            continue
        bars = cache.get(code)
        if bars is None:
            n_no_code += 1
            continue
        dmap = idx_maps[code]
        i = dmap.get(d)
        if i is None:
            # bisect fallback for D bar missing in kline
            lo, hi = 0, len(bars)
            while lo < hi:
                mid = (lo + hi) // 2
                if bars[mid]["date"] < d:
                    lo = mid + 1
                else:
                    hi = mid
            if lo < len(bars) and bars[lo]["date"] > d:
                nxt = bars[lo]
            else:
                nxt = None
            if nxt is None:
                n_unbuyable += 1
                continue
            expected_next = calendar_next(calendar, d)
            if expected_next is not None and nxt["date"] != expected_next:
                n_suspended += 1
                continue
            open_next = nxt["open"]
            if nxt.get("volume", 0) <= 0:
                n_unbuyable += 1
                continue
        else:
            cache_close_d = bars[i].get("close")
            if cache_close_d is not None and abs(cache_close_d - close_d) > 0.01:
                n_adj_mismatch += 1
                continue
            if i + 1 >= len(bars):
                n_unbuyable += 1
                continue
            expected_next = calendar_next(calendar, d)
            if expected_next is not None and bars[i + 1]["date"] != expected_next:
                n_suspended += 1
                continue
            open_next = bars[i + 1]["open"]
            if bars[i + 1].get("volume", 0) <= 0:
                n_unbuyable += 1
                continue
        if open_next is None or open_next <= 0:
            n_unbuyable += 1
            continue
        gap, cost_pct, _gross = gap_net_return(
            close_d, open_next, entry_date=d, size=TRADE_SIZE,
        )
        returns.append(gap)
        costs.append(cost_pct)
        dates.append(d)
    return (
        returns, dates, costs,
        n_unbuyable, n_no_code, n_bad_close, n_suspended, n_adj_mismatch,
    )


# ─── regime computation (3-way: bull/bear/range) ───────────────────────

def _load_regime_cache() -> list[tuple[str, float, float]] | None:
    """Load index_ma20_regime.json -> sorted [(date, close, ma20), ...].

    The cache has binary strong/weak labels; we ignore them and compute our
    own 3-way from close + ma20 + slope.
    """
    if not REGIME_CACHE.exists():
        return None
    with open(REGIME_CACHE, encoding="utf-8") as f:
        raw = json.load(f)
    rows: list[tuple[str, float, float]] = []
    for d, v in raw.items():
        c = v.get("close")
        m = v.get("ma20")
        if c is not None and m is not None:
            rows.append((d, float(c), float(m)))
    rows.sort(key=lambda x: x[0])
    print(f"[regime] cache loaded: {len(rows)} dates "
          f"({rows[0][0]} -> {rows[-1][0]})")
    return rows


def _fetch_index_bars_baostock() -> list[dict]:
    """Fallback: fetch sh.000001 daily close from baostock (if cache missing)."""
    try:
        from data.sources.baostock_src import fetch_bars  # noqa: PLC0415
        bars = fetch_bars(
            "sh.000001", "2025-11-01", "2026-09-06",
            fields="date,close", adjustflag="3",  # no adjust for index
        )
        return bars
    except Exception:
        # direct baostock fallback (inline, same as platform_breakout_lift.py)
        import baostock as bs  # noqa: PLC0415
        bars: list[dict] = []
        try:
            bs.login()
            rs = bs.query_history_k_data_plus(
                "sh.000001", "date,close",
                start_date="2025-11-01", end_date="2026-09-06",
            )
            while rs.error_code == "0" and rs.next():
                row = rs.get_row_data()
                if row[1]:
                    bars.append({"date": row[0], "close": float(row[1])})
            bs.logout()
        except Exception as e:  # noqa: BLE001
            print(f"[regime] baostock fetch failed: {e}")
        return bars


def compute_regime_labels() -> dict[str, str]:
    """Compute 3-way regime (bull/bear/range) per trading date.

    bull  = close > MA20 AND MA20_slope > 0  (above rising trend)
    bear  = close < MA20 AND MA20_slope < 0  (below falling trend)
    range = everything else

    MA20_slope = (ma20_today - ma20_prev_trading_day) / ma20_prev_trading_day.
    Consecutive entries in the sorted cache = consecutive trading days
    (baostock returns trading days only, weekends/holidays excluded).

    Returns {date_str: "bull" | "bear" | "range"}.
    """
    rows = _load_regime_cache()
    if rows is None:
        print("[regime] cache not found, fetching from baostock ...")
        bars = _fetch_index_bars_baostock()
        if not bars:
            print("[regime] FATAL: no index data, cannot classify regime")
            return {}
        closes = sorted(
            ((b["date"], float(b["close"])) for b in bars if b.get("close")),
            key=lambda x: x[0],
        )
        rows = []
        for i, (d, c) in enumerate(closes):
            if i < MA_WINDOW - 1:
                continue
            ma20 = sum(closes[j][1] for j in range(i - MA_WINDOW + 1, i + 1)) / MA_WINDOW
            rows.append((d, c, ma20))
        print(f"[regime] computed from baostock: {len(rows)} dates")

    # compute MA20 slope from consecutive sorted entries
    regime: dict[str, str] = {}
    for i, (d, close, ma20) in enumerate(rows):
        if i == 0:
            regime[d] = "range"  # no prev ma20 for slope
            continue
        prev_ma20 = rows[i - 1][2]
        if prev_ma20 == 0:
            regime[d] = "range"
            continue
        slope = (ma20 - prev_ma20) / prev_ma20
        above = close > ma20
        rising = slope > 0
        below = close < ma20
        falling = slope < 0
        if above and rising:
            regime[d] = "bull"
        elif below and falling:
            regime[d] = "bear"
        else:
            regime[d] = "range"

    # distribution (all dates in cache)
    counts = {"bull": 0, "bear": 0, "range": 0}
    for v in regime.values():
        counts[v] += 1
    total = len(regime)
    print(f"[regime] distribution (all {total} cached dates): "
          f"bull={counts['bull']}({counts['bull']*100/total:.1f}%) "
          f"bear={counts['bear']}({counts['bear']*100/total:.1f}%) "
          f"range={counts['range']}({counts['range']*100/total:.1f}%)")
    return regime


# ─── stratification + stats ────────────────────────────────────────────

def stratify_gap(
    returns: list[float],
    dates: list[str],
    regime_map: dict[str, str],
) -> tuple[dict[str, list[float]], dict[str, dict[str, list[float]]], int]:
    """Split gap returns by regime tag.

    Returns:
      by_regime: {regime: [net_returns...]}  (pooled per regime)
      by_regime_day: {regime: {date: [net_returns...]}}  (day-clustered)
      n_untagged: trades whose date has no regime label
    """
    by_regime: dict[str, list[float]] = {"bull": [], "bear": [], "range": []}
    by_regime_day: dict[str, dict[str, list[float]]] = {
        "bull": {}, "bear": {}, "range": {},
    }
    n_untagged = 0
    for ret, d in zip(returns, dates):
        tag = regime_map.get(d)
        if tag is None:
            n_untagged += 1
            continue
        by_regime[tag].append(ret)
        by_regime_day[tag].setdefault(d, []).append(ret)
    return by_regime, by_regime_day, n_untagged


def regime_stats(
    returns_list: list[float],
    by_day: dict[str, list[float]],
) -> dict:
    """Compute per-regime statistics.

    Includes both pooled t-stat (naive, inflates n) and day-clustered t-stat
    (honest, each day weighted equally — same as s44_gap_run_60d's approach).
    """
    arr = np.asarray(returns_list, dtype=float)
    n = arr.size
    n_days = len(by_day)
    if n == 0:
        return {
            "n_picks": 0, "n_days": 0,
            "net_mean_pct": None, "median_pct": None,
            "win_rate": None, "std_pct": None,
            "pooled_t_stat": None, "day_clustered_t_stat": None,
            "day_mean_pct": None,
        }
    net_mean_pct = float(arr.mean()) * 100
    median_pct = float(np.median(arr)) * 100
    win_rate = float((arr > 0).mean())
    std_pct = float(arr.std(ddof=1)) * 100 if n > 1 else 0.0
    pooled_t = (
        net_mean_pct / (std_pct / (n ** 0.5))
        if n > 1 and std_pct > 0 else 0.0
    )

    # day-clustered (honest: each day = 1 observation)
    day_means = [float(np.mean(rs)) for rs in by_day.values()]
    day_mean_pct = float(np.mean(day_means)) * 100 if day_means else 0.0
    if len(day_means) > 1:
        day_arr = np.asarray(day_means, dtype=float)
        day_std = float(day_arr.std(ddof=1))
        day_t = (
            day_mean_pct / (day_std / (len(day_means) ** 0.5))
            if day_std > 0 else 0.0
        )
    else:
        day_t = 0.0

    return {
        "n_picks": n,
        "n_days": n_days,
        "net_mean_pct": round(net_mean_pct, 4),
        "median_pct": round(median_pct, 4),
        "win_rate": round(win_rate, 4),
        "std_pct": round(std_pct, 4),
        "pooled_t_stat": round(pooled_t, 4),
        "day_clustered_t_stat": round(day_t, 4),
        "day_mean_pct": round(day_mean_pct, 4),
    }


# ─── main ───────────────────────────────────────────────────────────────

def main():
    # 1. load data
    fbs = load_universe()
    cache, idx_maps, calendar = build_kline_index()
    regime_map = compute_regime_labels()
    if not regime_map:
        print("[FATAL] no regime labels, aborting")
        return

    # 2. compute gap series (same as s44_gap_run_60d)
    returns, dates, costs, n_unbuyable, n_no_code, n_bad_close, n_suspended, n_adj_mm = \
        compute_gap_series(fbs, cache, idx_maps, calendar)
    arr = np.asarray(returns, dtype=float)
    n = arr.size
    overall_net = float(arr.mean()) * 100 if n else 0.0
    overall_win = float((arr > 0).mean()) if n else 0.0
    overall_days = len(set(dates))

    print(f"\n=== OVERALL (120d baseline, real cost) ===")
    print(f"n picks={n}  n unbuyable={n_unbuyable}  n suspended={n_suspended}")
    print(f"  n adj_mismatch={n_adj_mm}  n no_code={n_no_code}  n bad_close={n_bad_close}")
    print(f"  net_mean={overall_net:.4f}%  win_rate={overall_win:.4f}  days={overall_days}")

    # 3. regime distribution within the 120 universe dates
    uni_dates = sorted(set(dates))
    regime_in_uni = {tag: 0 for tag in ("bull", "bear", "range")}
    n_untagged_dates = 0
    for d in uni_dates:
        tag = regime_map.get(d)
        if tag is None:
            n_untagged_dates += 1
        else:
            regime_in_uni[tag] += 1
    print(f"\n=== REGIME DISTRIBUTION (120 universe dates) ===")
    for tag in ("bull", "bear", "range"):
        cnt = regime_in_uni[tag]
        pct = cnt * 100 / len(uni_dates) if uni_dates else 0
        print(f"  {tag:5s}: {cnt:3d} days ({pct:.1f}%)")
    if n_untagged_dates:
        print(f"  untagged: {n_untagged_dates} dates (not in regime cache)")

    # 4. stratify gap returns by regime
    by_regime, by_regime_day, n_untagged = stratify_gap(returns, dates, regime_map)
    if n_untagged:
        print(f"\n[regime] WARNING: {n_untagged} trades have no regime tag")

    # 5. per-regime stats
    print(f"\n=== REGIME STRATIFIED GAP NET RETURN ===")
    results: dict[str, dict] = {}
    for tag in ("bull", "bear", "range"):
        rets = by_regime[tag]
        by_day = by_regime_day[tag]
        stats = regime_stats(rets, by_day)
        results[tag] = stats
        print(f"\n--- {tag.upper()} ---")
        if stats["n_picks"] == 0:
            print("  no trades in this regime")
            continue
        print(f"  n_picks={stats['n_picks']}  n_days={stats['n_days']}")
        print(f"  net_mean (pooled)  = {stats['net_mean_pct']:.4f}%")
        print(f"  day_mean (clustered)= {stats['day_mean_pct']:.4f}%")
        print(f"  median             = {stats['median_pct']:.4f}%")
        print(f"  win_rate           = {stats['win_rate']:.4f}")
        print(f"  std                = {stats['std_pct']:.4f}%")
        print(f"  pooled t-stat      = {stats['pooled_t_stat']:.4f}  (naive, inflates n)")
        print(f"  day-clustered t-stat= {stats['day_clustered_t_stat']:.4f}  (honest)")

    # 6. per-regime §44v2 event verdict (optional, S168 wiring pattern)
    print(f"\n=== PER-REGIME §44v2 EVENT VERDICT ===")
    try:
        from tools._s44_wire import wire_verdict  # noqa: E402
        avg_cost_ratio = float(np.mean(costs) / 100.0) if costs else 0.0
        for tag in ("bull", "bear", "range"):
            rets = by_regime[tag]
            dts = []
            for d in sorted(by_regime_day[tag].keys()):
                dts.extend([d] * len(by_regime_day[tag][d]))
            if len(rets) < 2:
                print(f"  gap_regime:{tag} -> SKIPS (n={len(rets)} < 2)")
                continue
            v = wire_verdict(
                line_id=f"gap_regime:{tag}",
                returns=rets,
                edge_type="event",
                frozen_commit=FROZEN_COMMIT,
                dates=dts,
                n_comparisons=3,  # Bonferroni K=3 (bull/bear/range)
                round_trip_cost=avg_cost_ratio,
                script="tools/gap_regime_stratified.py",
                params={
                    "regime": tag,
                    "cost_model": "accounting.gap_net_return",
                    "trade_size": TRADE_SIZE,
                },
            )
            results[tag]["verdict_status"] = v.status
            results[tag]["verdict_note"] = v.note
    except Exception as e:
        print(f"  [s44_wire] per-regime verdict skipped: {e}")

    # 7. honest conclusion
    print(f"\n=== HONEST CONCLUSION ===")
    neg_regimes = []
    pos_regimes = []
    for tag in ("bull", "bear", "range"):
        s = results[tag]
        if s["n_picks"] == 0:
            continue
        if s["net_mean_pct"] is not None and s["net_mean_pct"] < 0:
            neg_regimes.append(tag)
        elif s["net_mean_pct"] is not None and s["net_mean_pct"] > 0:
            pos_regimes.append(tag)

    # regime balance check
    max_share = max(regime_in_uni.values()) / len(uni_dates) if uni_dates else 0
    dominant = max(regime_in_uni, key=regime_in_uni.get)
    print(f"  regime balance: bull={regime_in_uni['bull']} "
          f"bear={regime_in_uni['bear']} range={regime_in_uni['range']} "
          f"(of {len(uni_dates)} days)")
    print(f"  dominant regime: {dominant} ({max_share:.1%} of days)")
    print(f"  gap net negative in: {neg_regimes if neg_regimes else 'none'}")
    print(f"  gap net positive in: {pos_regimes if pos_regimes else 'none'}")

    if pos_regimes and neg_regimes:
        print("  -> REGIME-DEPENDENT: gap is positive in some regimes, negative in others.")
        print("     The overall negative result may be regime-skewed, NOT a uniform edge failure.")
        print("     BUT: check n_days + day-clustered t-stat per regime before concluding.")
        print("     Small-n regimes are exploratory (underpowered), not validated.")
    elif neg_regimes and not pos_regimes:
        print("  -> NOT A REGIME ARTIFACT: gap net is negative in ALL regimes.")
        print("     The negative result holds across bull/bear/range — gap is genuinely")
        print("     negative after real cost, regardless of market regime.")
    elif pos_regimes and not neg_regimes:
        print("  -> REGIME-POSITIVE: gap net is positive in ALL sampled regimes.")
        print("     (unexpected — recheck cost model + regime labeling)")
    else:
        print("  -> INSUFFICIENT DATA: no regime has enough trades to conclude.")

    # underpowered warning for small regimes
    for tag in ("bull", "bear", "range"):
        s = results[tag]
        if s["n_picks"] == 0:
            continue
        if s["n_days"] < 30:
            print(f"  WARNING: {tag} regime has only {s['n_days']} days "
                  f"(< 30) -> EXPLORATORY, not validated.")
        if s.get("day_clustered_t_stat") is not None:
            t = s["day_clustered_t_stat"]
            if abs(t) < 2.0:
                print(f"  NOTE: {tag} day-clustered t={t} (< 2.0) -> not significant.")

    print("\nDONE.")


if __name__ == "__main__":
    main()
